### ISSUE TITLE
Updater Error in logs

### ISSUE THREAD

**Issue by vampiricwulf** [SteveCastle/loki#60]
```
[2024-01-08 13:13:13.697] [info]  Checking for update
[2024-01-08 13:13:14.858] [error] Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/stevecastle/loki/releases/download/v2.0.3/latest.yml): HttpError: 404 
"method: GET url: https://github.com/stevecastle/loki/releases/download/v2.0.3/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 08 Jan 2024 21:13:11 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "46DE:9743:A3AE44:AAE16A:659C6567"
}
    at createHttpError (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\builder-util-runtime\out\httpExecutor.js:14:12)
    at o.handleResponse (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\builder-util-runtime\out\httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\builder-util-runtime\out\httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49128)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
    at Object.newError (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\builder-util-runtime\out\index.js:47:19)
    at rawData (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\electron-updater\out\providers\GitHubProvider.js:108:50)
    at t.GitHubProvider.info [as getLatestVersion] (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\electron-updater\out\providers\GitHubProvider.js:115:13)
    at g.result [as getUpdateInfoAndProvider] (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\electron-updater\out\AppUpdater.js:319:13)
    at g.doCheckForUpdates (C:\Users\Wulf\AppData\Local\Programs\loki\resources\app.asar\dist\main\webpack:\loki\node_modules\electron-updater\out\AppUpdater.js:333:15)
```

**Comment by SteveCastle** [comment]
I never really took the time to get auto updating working, but I will look into what I need to do to make it work.
